### ISSUE TITLE
no channel greater then 62 ?

### ISSUE THREAD

**Issue by antimodular** [jimparis/DmxReceiver#1]
i am running this sketch with your library and it works fine as long as i am sending data to channel 0 -62.
http://pastebin.com/uU2Renbz
channels above that do not react and get 0.

is there a limit in your library ?

when i run the same code with the library i downloaded in 2013 it works fine.

thanks,stephan

**Comment by antimodular** [comment]
update:
the posted code has this DMX.bufferService(); commented out.
the code work as mentioned but only up to channel 62

when using DMX.bufferService(); the code work also beyond 62.
?

**Comment by jimparis** [comment]
Yeah, you need to call `bufferService()` frequently in the current code.  In the included `DmxTest` example, this is done automatically in a timer interrupt.
