### ISSUE TITLE
Issue with some DMX transmitters

### ISSUE THREAD

**Issue by alfo** [jimparis/DmxReceiver#4]
I honestly don't know enough about the structure of DMX to know how to fix this, but with some sources (including the Chinese wireless DMX receivers readily available on eBay, and Pathport nodes on any speed setting), I get a read out of some channels as being permanently at 254, with the rest being at 0.

The divide (usually chan >309 is 0 and chan <= 309 at 254) depends on which speed setting I have the node at.

I imagine this is something to do with (variable?) timing of different parts of the signal. Unfortunately I don't own an oscilloscope to observe the difference between the DMX produced by the problematic sources and a known working source (an old DJ-style 192-channel desk).

Any suggestions as to how I could get this working with a wider range of sources?
<img width="2372" alt="screen shot 2016-09-28 at 17 22 28" src="https://cloud.githubusercontent.com/assets/1206159/18922922/6b7e5b50-85a2-11e6-9c51-242f7d34e275.png">

**Comment by alfo** [comment]
Well I feel really dumb - there's no problem with the library, my MAX485 had been fried at some point so was spewing garbage. Replaced it and working as intended.

**Comment by jimparis** [comment]
No problem!  Good luck with your project.
